In [23]:
# Le librerie dei framework specifici:
import matplotlib.pyplot as plt # Motore grafico di python per realizzare diagrammi e fuznoni
import numpy as np # Libreria che gestisce ad altissima efficienza gli array
import seaborn as sns # Libreria che usa il motore grafico di MatplotLib con funzionalita'

import numpy as np
import random
def initialize_game(horse_default_position=True):
    # TODO: implenentare la possibilita' di definire una posizione random
    board = np.zeros((8,8))
    positions = [(0,1), (0,6), (7,1), (7,6)]
    start_position = random.choice(positions)
    # Posioniamo il cavallo nella sua posizione iniziale
    board[start_position] = 1    

    # print(board)
    return board
    


# Scrviamo una funzione che legge una board e restituisce:
# - il numero di mosse raggunto dal cavallo
# - una tupla con la posizione attuale, orizzontale e verticale
def get_horse_current_position(board):
    current_move_number = board.max()
    current_h, current_v = np.unravel_index(board.argmax(), (8, 8))

    return current_move_number, (current_h, current_v)



# Scriviamo una funzione che legge una board e restituisce una lista delle possibili mosse disponibili
def get_available_moves(board):

    possible_movements = [(2,1),
                          (2,-1),
                          (-2,1),
                          (-2,-1),
                          (1,2),
                          (1,-2),
                          (-1,2),
                          (-1,-2)]

    _, current_horse_position = get_horse_current_position(board)
    h_pos, v_pos = current_horse_position
    
    available_moves = []

    for move in possible_movements:
        h_move, v_move = move
        new_h_pos = h_pos + h_move
        new_v_pos = v_pos + v_move
        if 0<=new_h_pos<=7:
            if 0<=new_v_pos<=7:
                if board[(new_h_pos,new_v_pos)] == 0:
                    available_moves.append((new_h_pos,new_v_pos))

        

    return available_moves
    


# Scriviamo una funzione che date le mosse a disposizione, ne sceglie casualmente una e la restituisce
def random_move(available_moves):

    return random.choice(available_moves)



# Scriviamo una funzione che legge una board e fa fare al cavallo una mossa scegliendo tra le disponibili casualmente

def move_horse(board):

    current_move, _ = get_horse_current_position(board)
    next_move_count = current_move + 1

    available_moves = get_available_moves(board)
    if len(available_moves)==0:
        return "Game Over"
    next_move = random_move(available_moves)
    board[next_move] = next_move_count
    
    return board


# Scriviamo una funzione che gioca una partita completa sino a che il cavallo non puo' piu' muoversi
# A fine partita, se il parametro "verbose" e' impostato su true, stampa a video la board.
# Restituisce la board
def play_one_game(verbose = False, horse_default_start_position = True):

    board= initialize_game()
    print(board)
    # board = move_horse(board)

    
    
play_one_game()

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
